### ISSUE TITLE
依赖最新的ChartHelper,为何还需要单独依赖MPAndroidChart

### ISSUE THREAD

**Issue by lydlovezjr** [chenyy0708/ChartHelper#4]
<img width="701" alt="微信截图_20200506094303" src="https://user-images.githubusercontent.com/19246347/81131533-09b92000-8f7e-11ea-8944-7aacfc78cec9.png">
不依赖MPAndroidChart的话.
MPAndroidChart的相关api都爆红.
然后项目运行不起来

**Comment by chenyy0708** [comment]
因为我内部是用的implementation,这个表示只在module内访问，也就是你的app模块无法访问这个依赖库的代码
